stages:
 - install
 - test
 - deploy

dependencies:
 stage: install
 image: node:12-alpine
 script:
  - npm install

test:
 stage: test
 image: trion/ng-cli-karma
 allow_failure: true
 script:
  - npm install
  - npm test
deploy:
 stage: deploy
 script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=aot-anime --api-key=223755e5-ea4f-4fdb-9d08-a7347b975674